apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xbfc1aetm-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-77be01b07e.nvvn.p3.openshiftapps.com/rhtap/rhtap-qe:c0d9b18ca610714bab36c7b50ded6e621b0d3843@sha256:42ae75dfecac6795d93de5f140bc11a5c1318d5dd9bfec9d06872641e874783d
          name: container-image
