apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xbfc1aetm-python
  janus-idp.io/tekton: xbfc1aetm-python
  backstage.io/kubernetes-id: xbfc1aetm-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xbfc1aetm-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
